AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Self contained stack hosting all our ECR repositories.

Parameters:
  pEnvironment:
    Type: String

Mappings:
  EcrPolicy:
    NonProd:
      EcrLifecyclePolicyText: |
        {
          "rules": [
            {
              "rulePriority": 1,
              "description": "Expire untagged images after a day",
              "selection": {
                "tagStatus": "untagged",
                "countType": "sinceImagePushed",
                "countUnit": "days",
                "countNumber": 1
              },
              "action": {
                "type": "expire"
              }
            },
            {
              "rulePriority": 2,
              "description": "Expire temp stack images after 2 days",
              "selection": {
                "tagStatus": "tagged",
                "tagPrefixList": [ "temp-" ],
                "countType": "sinceImagePushed",
                "countUnit": "days",
                "countNumber": 2
              },
              "action": {
                "type": "expire"
              }
            },
            {
              "rulePriority": 3,
              "description": "Only keep last 3 tagged images that have been deployed by CI",
              "selection": {
                "tagStatus": "tagged",
                "tagPrefixList": [ "ci-" ],
                "countType": "imageCountMoreThan",
                "countNumber": 3
              },
              "action": {
                "type": "expire"
              }
            }
          ]
        }
    Prod:
      EcrLifecyclePolicyText: |
        {
          "rules": [
            {
              "rulePriority": 1,
              "description": "Expire untagged images after a day",
              "selection": {
                "tagStatus": "untagged",
                "countType": "sinceImagePushed",
                "countUnit": "days",
                "countNumber": 1
              },
              "action": {
                "type": "expire"
              }
            },
            {
              "rulePriority": 2,
              "description": "Only keep last 30 tagged images that have been deployed by CI",
              "selection": {
                "tagStatus": "tagged",
                "countType": "imageCountMoreThan",
                "countNumber": 30
              },
              "action": {
                "type": "expire"
              }
            }
          ]
        }

Conditions:
  cIsProd: !Equals [!Ref pEnvironment, 'prod']

Resources:
  InventoryServiceRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: inventory-service-repository
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText:
          !If
            - cIsProd
            - !FindInMap [EcrPolicy, Prod, EcrLifecyclePolicyText]
            - !FindInMap [EcrPolicy, NonProd, EcrLifecyclePolicyText]

  CustomersServiceRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: customers-service-repository
      ImageTagMutability: IMMUTABLE
      LifecyclePolicy:
        LifecyclePolicyText:
          !If
            - cIsProd
            - !FindInMap [EcrPolicy, Prod, EcrLifecyclePolicyText]
            - !FindInMap [EcrPolicy, NonProd, EcrLifecyclePolicyText]

Outputs:
  oInventoryServiceRepositoryUri:
    Description: Inventory Service Repository Uri
    Value: !GetAtt InventoryServiceRepository.RepositoryUri
  oCustomersServiceRepositoryUri:
    Description: Customers Service Repository Uri
    Value: !GetAtt CustomersServiceRepository.RepositoryUri
