AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Self contained stack hosting all our ECR repositories.

Resources:
  InventoryServiceRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: inventory-service-repository
      ImageTagMutability: IMMUTABLE

Outputs:
  oInventoryServiceRepositoryUri:
    Description: Inventory Service Repository Uri
    Value: !GetAtt InventoryServiceRepository.RepositoryUri
